### ISSUE TITLE
Created access path does not get assigned to created and mounted VHDX 

### ISSUE THREAD

**Issue by milanche1311** [sqlcollaborative/PSDatabaseClone#43]
**Before submitting the bug**
- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [X] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

**Describe the bug**
When using New-PSDCImage a vhdx file is created and access path where backed up database will be restored as image. The restore process finishes but the folder gets deleted and virtual drive remains empty. I realized that when created vhdx is mounted it does not get assigned path to created folder in order to store database image in it.

**To Reproduce**

<#
#this part of the code does not provide proper values 
#Get the properties of the disk and partition
          $disk = $diskResult.Disk
          $partition = $diskResult.Partition

#For this part of the code
     # Add the access path to the mounted disk
                    if ($computer.IsLocalhost) {
                        $null = Add-PartitionAccessPath -DiskNumber $disk.Number -PartitionNumber $partition[1].PartitionNumber -AccessPath $accessPath -ErrorAction SilentlyContinue
                    }
                    else {
                        $command = [ScriptBlock]::Create("Add-PartitionAccessPath -DiskNumber $($disk.Number) -PartitionNumber $($partition[1].PartitionNumber) -AccessPath $accessPath -ErrorAction SilentlyContinue")
                        $null = Invoke-PSFCommand -ComputerName $computer -ScriptBlock $command -Credential $DestinationCredential

#>
```

**Expected behavior**
When I copied next code used in New-PSDCClone for mounting the created vhd clone instead of - "#Get the properties of the disk and partition" - part, I got correct results. The image was saved in virtual drive

#BEGIN
$disk = Get-Disk | Where-Object {$_.Location -eq "$accessPath.vhdx"}

                # Mounting disk to access path

      if ($PSCmdlet.ShouldProcess($disk.Number, "Mounting volume to accesspath")) {
                    try {
                        # Check if computer is local
                        if ($computer.IsLocalhost) {
                            # Get the partition based on the disk
                            $partition = Get-Partition -Disk $disk

                            # Create an access path for the disk
                            $null = Add-PartitionAccessPath -DiskNumber $disk.Number -PartitionNumber $partition[1].PartitionNumber -AccessPath $accessPath -ErrorAction SilentlyContinue
                        }
                        else {
                            $command = [ScriptBlock]::Create("Get-Partition -DiskNumber $($disk.Number)")
                            $partition = Invoke-PSFCommand -ComputerName $computer -ScriptBlock $command -Credential $Credential

                            $command = [ScriptBlock]::Create("Add-PartitionAccessPath -DiskNumber $($disk.Number) -PartitionNumber $($partition[1].PartitionNumber) -AccessPath '$accessPath' -ErrorAction Ignore")

                            $null = Invoke-PSFCommand -ComputerName $computer -ScriptBlock $command -Credential $Credential
                        }

                    }
                    catch {
                        Stop-PSFFunction -Message "Couldn't create access path for partition" -ErrorRecord $_ -Target $partition -Continue
                    }
                }
#END



**Environmental data**

 - PowerShell: 
![image](https://user-images.githubusercontent.com/42850146/52449816-e87a4180-2b38-11e9-9bba-382a160362c1.png)

**Comment by sanderstad** [comment]
I will look into this and see what's going on

**Comment by MegaVik** [comment]
Any update? I have the same situation. On Windows Server 2016 I am able to create an image but on WS 2012 I am getting next errors: 
WARNING: [12:31:39][New-PSDCImage] Couldn't initialize vhd C:\temp\Task1_20190401123135.vhdx
WARNING: [12:31:39][New-PSDCImage] Couldn't create access path for partition

**Comment by walotehit** [comment]
Can you guys please clarify which one of this files need modification and where?

New-PSDCImage.ps1
OR
New-PSDCClone.ps1

**Comment by sanderstad** [comment]
I have made several changes and pushed to the development branch. 
I have not been able to create a well enough test environment to get the same kind of errors.
If you could test it from the development branch and tell me if you still have the problem, that would be great.
