### ISSUE TITLE
New-PDSCClone Mount-DbaDatabase failure

### ISSUE THREAD

**Issue by jsreynolds** [sqlcollaborative/PSDatabaseClone#45]
**Describe the bug**
SQL 2017, local home install, no weird permission issues or the like. All software up to date.

With or without Windows or sa credentials, I get the same error after running against a freshly created image:

`New-PSDCClone -SqlInstance localhost -SqlCredential $cred -Database AdventureWorks2017 -CloneName AdventureWorks2017_clone  -Destination C:\Clone -LatestImage`

Error
`WARNING: [22:39:05][Mount-DbaDatabase] Failure | At least one file is needed for Database Attach.`

And nothing is attached of course in SSMS.

**Comment by milanche1311** [comment]
This resembles the issue that I reported but the cause is in image creation in New-PSDCImage.

Take a look at #43 there is the example how to resolve it. Try editing the function like in example and see if that resolves your issue.

Interesting thing is that I tried those cmdlets on several machine and not all got to that issue.

**Comment by jsreynolds** [comment]
@milanche1311 I tried what I hope I read correctly, replacing the code in `New-PSDCImage.ps1` as follows below, but I still receive the same error. Did I miss something by chance?

`
                # Get the properties of the disk and partition
                # $disk = $diskResult.Disk
                # $partition = $diskResult.Partition

                # if ($PSCmdlet.ShouldProcess($accessPath, "Adding access path '$accessPath' to mounted disk")) {
                #     # Add the access path to the mounted disk
                #     if ($computer.IsLocalhost) {
                #         $null = Add-PartitionAccessPath -DiskNumber $disk.Number -PartitionNumber $partition[1].PartitionNumber -AccessPath $accessPath -ErrorAction SilentlyContinue
                #     }
                #     else {
                #         $command = [ScriptBlock]::Create("Add-PartitionAccessPath -DiskNumber $($disk.Number) -PartitionNumber $($partition[1].PartitionNumber) -AccessPath $accessPath -ErrorAction SilentlyContinue")
                #         $null = Invoke-PSFCommand -ComputerName $computer -ScriptBlock $command -Credential $DestinationCredential
                #     }
                # }
                
                $disk = Get-Disk | Where-Object {$_.Location -eq "$accessPath.vhdx"}

                # Mounting disk to access path

                if ($PSCmdlet.ShouldProcess($disk.Number, "Mounting volume to accesspath")) {
                    try {
                        # Check if computer is local
                        if ($computer.IsLocalhost) {
                            # Get the partition based on the disk
                            $partition = Get-Partition -Disk $disk

                            # Create an access path for the disk
                            $null = Add-PartitionAccessPath -DiskNumber $disk.Number -PartitionNumber $partition[1].PartitionNumber -AccessPath $accessPath -ErrorAction SilentlyContinue
                        }
                        else {
                            $command = [ScriptBlock]::Create("Get-Partition -DiskNumber $($disk.Number)")
                            $partition = Invoke-PSFCommand -ComputerName $computer -ScriptBlock $command -Credential $Credential

                            $command = [ScriptBlock]::Create("Add-PartitionAccessPath -DiskNumber $($disk.Number) -PartitionNumber $($partition[1].PartitionNumber) -AccessPath '$accessPath' -ErrorAction Ignore")

                            $null = Invoke-PSFCommand -ComputerName $computer -ScriptBlock $command -Credential $Credential
                        }

                    }
                    catch {
                        Stop-PSFFunction -Message "Couldn't create access path for partition" -ErrorRecord $_ -Target $partition -Continue
                    }
                }  
`

**Comment by milanche1311** [comment]
Two things:
1. Just make sure that you re-imported changed function to PowerShell
2. The section - # Add the access path to the mounted disk - should not be commented out, this should remain active and placed AFTER the inserted code

This section should be removed/commented out
#Get the properties of the disk and partition
$disk = $diskResult.Disk
$partition = $diskResult.Partition

Try again with those instructions

To check what is going on, after using New-PSDCImage you will are supposed to get a vhdx file larger than 300MB (300MB for base file + N MBs for database). If the virtual drive file remains at 300MB that means that routine above is not working properly (database image is not stored in the file)

**Comment by walotehit** [comment]
Hey guys I am having the same issue - have you figured it out?

WARNING: [22:39:05][Mount-DbaDatabase] Failure | At least one file is needed for Database Attach

![image](https://user-images.githubusercontent.com/31934600/68885214-f6658000-06d1-11ea-9024-0754a2b69363.png)

**Comment by sanderstad** [comment]
I'm currently reworking the module to make it work more efficient. I hope to get most of the bugs fixed somewhere next week

**Comment by walotehit** [comment]
> 
> 
> I'm currently reworking the module to make it work more efficient. I hope to get most of the bugs fixed somewhere next week

Thanks sanderstad. I appreciate it. Please keep us posted!

**Comment by sanderstad** [comment]
I have made several changes and pushed to the development branch. 
I have not been able to create a well enough test environment to get the same kind of errors.
If you could test it from the development branch and tell me if you still have the problem, that would be great.

**Comment by walotehit** [comment]
Let me give it a shot and will let you know buddy. Thanks.

**Comment by walotehit** [comment]
sanderstad - Sorry I finally got some time to test this. I downloaded version 0.3.133 (that is the one I should use right?). Is this what you want me to do?

![image](https://user-images.githubusercontent.com/31934600/70575748-60076b80-1b64-11ea-999b-bca1809415b7.png)

**Comment by sanderstad** [comment]
Yesy, that’s the latest version.

 

Apparently you already have it installed somewhere which technically should not be a problem.

 

I would remove any previous versions and install it again using the Install-Module command

**Comment by walotehit** [comment]
So sanderstad, you mentioned you did some changes to fix the issue below. On what version are those changes included?

![image](https://user-images.githubusercontent.com/31934600/71010229-c16d9400-20a8-11ea-810b-18446cc3dabe.png)

**Comment by sanderstad** [comment]
On the newest version.

 

Does you SQL Server service have access to the clone folder?

**Comment by jsreynolds** [comment]
I just wanted to let you know I thought I ran into this again with the latest version release of (today), and it was indeed that my clone to folder did not have proper database engine security, just as you described. I was 5 seconds away from filing another issue when I saw, "4 issues like this one", clicked, saw this, and kept reading.
Thanks!
--J

**Comment by MoochingTusk** [comment]
I'm running version 0.3.61 and am getting the error. I've checked permissions for SQL Server on both the image location and the clone location. Any advice on resolving this would be much appreciated.

WARNING: [21:58:58][Mount-DbaDatabase] Failure | At least one file is needed for Database Attach.


CloneID       : 1
CloneLocation : C:\Clone\CloneTest2.vhdx
AccessPath    : C:\Clone\CloneTest2_brnBM
SqlInstance   : TESTINSTANCE
DatabaseName  : CloneTest2
IsEnabled     : True
ImageID       : 1
ImageName     : CloneTest_20200513215820
ImageLocation : \\testinstance\PSDatabaseClone\CloneTest_20200513215820.vhdx
HostName      : TESTINSTANCE
