### ISSUE TITLE
Remove-PSDCClone does not work with SQL Server named instances

### ISSUE THREAD

**Issue by bertvanlandeghem** [sqlcollaborative/PSDatabaseClone#47]
**Before submitting the bug**
- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

**Describe the bug**
Remove-PSDCClone does not work with SQL Server named instances specified by the -HostName parameter. The command does not error out, but skips the server. This is because the hostname is used to filter the ,[PSDatabaseClone].[dbo].[Host].[HostName] column, but this column contains the computer fqdn instead of COMPUTERNAME\INSTANCENAME.

**To Reproduce**
```powershell
Remove-PSDCClone -HostName DBSERVER\BVLTEST1 -Database DB1_Clone1 -Verbose
```

**Expected behavior**
The command should be able to connect to named instances to remove clones<

**Screenshots**

**Environmental data**
 - PowerShell: 
Name                           Value
----                           -----
PSVersion                      5.1.15063.1746
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.1746
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Additional context**
Related to https://github.com/sqlcollaborative/PSDatabaseClone/issues/44

**Comment by bertvanlandeghem** [comment]
Since PSDatabaseClone depends on dbatools anyway, I suggest the rename of parameter -HostName to -SqlInstance, and use the datatype DbaInstanceParameter (for an example see https://github.com/sqlcollaborative/dbatools/blob/development/functions/Connect-DbaInstance.ps1).  This class has all the different parameters needed.
```powershell
PS C:\WINDOWS\system32> [DbaInstanceParameter] 'MYDBSERVER\BVLTEST1'

ComputerName       : MYDBSERVER
InstanceName       : BVLTEST1
Port               : 0
NetworkProtocol    : Any
IsLocalHost        : False
FullName           : MYDBSERVER\BVLTEST1
FullSmoName        : MYDBSERVER\BVLTEST1
SqlComputerName    : [MYDBSERVER]
SqlInstanceName    : [BVLTEST1]
SqlFullName        : [MYDBSERVER\BVLTEST1]
IsConnectionString : False
Type               : Default
LinkedLive         : False
LinkedServer       :
InputObject        : MYDBSERVER\BVLTEST1
```

**Comment by sanderstad** [comment]
That would be a good idea. When this was first created dbatools was implementing this class and I wanted to wait a while to see how it would work.
But it's being used in every command within the dbatools module right now so I have no objections of implementing it within PSDatabaseClone

**Comment by sanderstad** [comment]
I've finally had the chance to look at the code but I think everything is handled correctly. 
But you actually don't have to assign the SQL instance. The way it works is that the command retrieves the clones for the host from the configuration.

So what you should execute is:
`Remove-PSDCClone -HostName DBSERVER -Database DB1_Clone1 -Verbose`

It will then figure out the instance name from the clone json data and remote the database and related files accordingly.

**Comment by sanderstad** [comment]
I have made several changes and pushed to the development branch. 
I have not been able to create a well enough test environment to get the same kind of errors.
If you could test it from the development branch and tell me if you still have the problem, that would be great.
