### ISSUE TITLE
New-PSDCClone Couldn't create access path for partition

### ISSUE THREAD

**Issue by abajwa369** [sqlcollaborative/PSDatabaseClone#55]
[New-PSDCClone] Couldn't create access path for partition | Cannot validate argument on parameter 'Disk'. The argument is null. Provide a valid value for the argument, and then try running the command again.

- was doing PSDatabaseclone set for the first time. 
- Image gets created, 
- Clone is also getting created, I can see it there in SELECT *   FROM [PSDatabaseClone].[dbo].[Clone] table. 
- Only thing is, If I run following command, I get this error:

**To reproduce:** 
Run Install-module PSDatabaseClone

**Setup config**
PS C:\Windows\system32> Set-PSDCConfiguration
[20:32:28][Set-PSDCConfiguration] Started PSDatabaseClone Setup

Choose your system
Where do you want your data to be saved?
[D] Database  [J] JSON  [?] Help (default is "D"): D
 - Please enter the SQL Server instance: MYSQLHost\MySQLInstance
 - Database Name [PSDatabaseClone]: PSDatabaseClone
 - Database Login:
 - Password:
[20:32:44][Set-PSDCConfiguration] All mandatory configurations have been made
[20:32:44][Set-PSDCConfiguration] Finished setting up PSDatabaseClone

**Create image:**
PS C:\Windows\system32> New-PSDCImage -SourceSqlInstance MYSQLHost\MySQLInstance -DestinationSqlInstance MYSQLHost\MySQLInstance -Database DB1 -ImageNetworkPath \\MySQLHost\NetworkShare\New\Images -CreateFullBackup -CopyOnlyBackup
WARNING: [20:36:17][New-PSDCImage] Couldn't initialize vhd E:\NetworkShare\New\Images\DB1_20190616203614.vhdx | A parameter cannot be found that matches parameter name 'DiskImage'.
WARNING: [20:36:17][New-PSDCImage] Couldn't create access path for partition | Cannot index into a null array.

Confirm
The item at E:\NetworkShare\New\Images\DB1_20190616203614 has children and the Recurse parameter was not specified.
If you continue, all children will be removed with the item. Are you sure you want to continue?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): Y

ImageID           : 5
ImageName         : DB1_20190616203614
ImageLocation     : \\MYSQLHost\NetworkShare\New\Images\DB1_20190616203614.vhdx
SizeMB            : 19
DatabaseName      : DB1
DatabaseTimestamp : 6/16/2019 8:36:15 PM
CreatedOn         : 1/1/0001 12:00:00 AM

**Create Clone**
PS C:\Windows\system32> New-PSDCClone -SqlInstance MYSQLHost\MySQLInstance -Destination E:\NetworkShare\New\Clone -CloneName DB1_CLONE1 -Database DB1 -LatestImage
Initialize-Disk : Cannot validate argument on parameter 'Number'. The argument is null. Provide a valid value for the
argument, and then try running the command again.
At line:439 char:57
+ ...                  $null = Initialize-Disk -Number $disk.Number -Partit ...
+                                                      ~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Initialize-Disk], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Initialize-Disk

**WARNING: [20:37:08][New-PSDCClone] Couldn't create access path for partition | Cannot validate argument on parameter 'Disk'. The argument is null. Provide a valid value for the argument, and then try running the command again.**

Here is the version of the module installed:
**Get-InstalledModule:
0.9.834    dbatools                            PSGallery
0.3.62     PSDatabaseClone                     PSGallery
1.0.19     PSFramework                         PSGallery**

Please advise if am doing something wrong. Thanks!

**Comment by Pozun1** [comment]
Hi, I Have same problem. 
Someone know how to fix??

**Comment by sanderstad** [comment]
I'm busy fixing a lot of things in the module. Have you tried using the development version?

**Comment by sanderstad** [comment]
I have made several changes and pushed to the development branch. 
I have not been able to create a well enough test environment to get the same kind of errors.
If you could test it from the development branch and tell me if you still have the problem, that would be great.
