### ISSUE TITLE
AccessRule "Everyone" on german systems

### ISSUE THREAD

**Issue by ivandrago666** [sqlcollaborative/PSDatabaseClone#60]
Hi,

I had problems during creation of a clone. After some research I found out, 
that this line caused the problem:

$accessRule = New-Object System.Security.AccessControl.FilesystemAccessrule("**Everyone**", "FullControl", "Allow")

The identifier "Everyone" will not be found on german systems. On these systems it's called "Jeder". 

My solution would be:

$everyone = [System.Security.Principal.WellKnownSidType]::WorldSid
$sid = New-Object System.Security.Principal.SecurityIdentifier($everyone, $Null)
$accessRule = New-Object System.Security.AccessControl.FilesystemAccessrule($sid, "FullControl", "Allow")

Would you agree with that?

Regards,
gg

**Comment by sanderstad** [comment]
That makes sense, great find.

 

In hindsight, I developed the module on an English system and never imagined it would work differently on other systems like that

 

Can you put that information in an issue. 

It has just been so very busy lately that I have not had the chance to fully work on this.

 

I will get back to this project very soon and will make a lot of changes including this.

 

 

Thanks again for finding this.

 

With kind regards,

 

Sander Stad
