### ISSUE TITLE
Cannot bind argument to parameter ComputerHame because it is null

### ISSUE THREAD

**Issue by ivandrago666** [sqlcollaborative/PSDatabaseClone#61]
Hi,

I'm getting an error when removing a clone.
Error message: Cannot bind argument to parameter ComputerHame because it is null

This is my result of my research:

The list of clones is grouped by the sqlinstance with this line:
$clones = $InputObject | Group-Object SqlInstance

Some lines later there is this line:
$computer = [PsfComputer]$clone.HostName

$clone is group object, not the clone itself, I guess that's the problem.

I think this could work, because the hostname should be the same when grouped by 
sqlinstance (?)
$computer = [PsfComputer]$clone.Group[0].HostName

Let me know if you need something else.

Awesome work by the way!

Regards,
gg

**Comment by sanderstad** [comment]
That’s a known error. If you use the development branch that should be fixed.

**Comment by sanderstad** [comment]
Is this still an issue with the development branch?

**Comment by sanderstad** [comment]
I have made several changes and pushed to the development branch. 
I have not been able to create a well enough test environment to get the same kind of errors.
If you could test it from the development branch and tell me if you still have the problem, that would be great.
