### ISSUE TITLE
Windows "Evaluation" Editions throws warning during Set-PSDCConfiguration

### ISSUE THREAD

**Issue by blitzmann** [sqlcollaborative/PSDatabaseClone#68]
**Describe the bug**
Ran into this while loading a Windows Server 2012 R2 VM while gathering more data for #67. I'm using the VHD image found here: https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2012-r2

This is the bit of code that checks for supported versions:

https://github.com/sqlcollaborative/PSDatabaseClone/blob/development/internal/scripts/preimport.ps1#L27

`Get-CimInstance Win32_OperatingSystem | Select-Object Caption, Description, Name, OSType, Version` outputs the following for this image:

```
Caption     : Microsoft Windows Server 2012 R2 Datacenter Evaluation
Description : DEVSQL
Name        : Microsoft Windows Server 2012 R2 Datacenter Evaluation|C:\Windows|\Device\Harddisk0\Partition1
OSType      : 18
Version     : 6.3.9600
```

I think an easy fix would be to lob off any "Evaluation" text found in `$osDetails`, as evaluation copies should be fully functional.

**To Reproduce**

Attempt to set configuration while Windows Server is under evaluation

**Expected behavior**
Be able to set configuration while Windows Server is under evaluation

**Environmental data**

 - PowerShell: 
```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.34003
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by sanderstad** [comment]
That would probably work. When I created that check i did not anticipate for any evaluation editions to appear because I was assuming that anyone using this would want to run this on a non-evaluation license.

I will look into that

**Comment by blitzmann** [comment]
Awesome, thanks @sanderstad!

I'm using an Evaluation to evaluate (lol) PSDC for use in our production systems. Instead of mucking around with production servers, I'm using these images to set up a sort of homelab and get a plan of action together to present to the powers that be so that deployment and workflow goes smoothly. 👍

**Comment by blitzmann** [comment]
@sanderstad Was able to test this out tonight, made a slight tweak and PR'd. Simply replacing "Evaluation" left a trailing space, which prevented the edition from matching correctly form the supported list

**Comment by sanderstad** [comment]
Saw that and merged it
