### ISSUE TITLE
Cannot create image using local path

### ISSUE THREAD

**Issue by blitzmann** [sqlcollaborative/PSDatabaseClone#69]
**Before submitting the bug**
- [ ] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

First one isn't checked because I can't get the "latest installed" (see #67). I am running off commit 650a806, which is the latest commit

**Describe the bug**

I don't have a network share up and running right now, so I'm trying to create an image to the local disk. This seems to be failing tho with an error: `The image network path  is not valid`. It seems that the script is expecting there be a network path parameter...

```
PS C:\Users\Administrator> New-PSDCImage -SourceSqlInstance DEVSQL -SourceSqlCredential $cred -DestinationSqlInstance DEVSQL -DestinationSqlCredential $cred -DestinationCredential $cred -ImageLocalPath C:\Images -Database AdventureWorks2014 -CreateFullBackup
WARNING: [20:11:15][New-PSDCImage] The image network path  is not valid | Exception calling ".ctor" with "1" argument(s): "Invalid URI: The URI is empty."
```

I should note that I can currently work around this by using the following parameter instead of `-ImageLocalPath`: `-ImageNetworkPath \\localhost\c$\Images`

**To Reproduce**

Attempt to use `-ImageLocalPath`, and note error.

**Expected behavior**

Expecting the script to take `-ImageLocalPath` and save images to that path

**Screenshots**

**Environmental data**

 - PowerShell: 
```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.34003
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by sanderstad** [comment]
So I got the chance to look into this.

I understand the confusion about the parameter ImageLocalPath.
The thing is that the command needs a UNC path and the variable ImageLocalPath, if not set, will be derived from the UNC path.

The other way round, from local path to UNC, is very hard to do.

I changed the checks to make sure this error doesn't occur anymore.

**Comment by blitzmann** [comment]
@sanderstad Maybe I'm still misunderstanding the purpose of the `-ImageLocalPath` parameter. From looking at the code in dev branch right now:

```
 # Check if the ImageLocalPath and convertedLocalPath are the same
                if ($ImageLocalPath -ne $convertedLocalPath) {
                    Stop-PSFFunction -Message "The local path '$ImageLocalPath' is not the same location as the network path '$ImageNetworkPath'" -Target $ImageNetworkPath
                    return
                }
```

I haven't had time to really dig into it, so forgive my ignorance, but from what I understand, there are two scenario here:
* `-ImageNetworkPath` supplied, `-ImageLocalPath` not supplied: This will take the `-ImageNetworkPath` and convert it to a local path, and that local path is then used in the commands
* `-ImageNetworkPath` supplied, `-ImageLocalPath` also supplied: This will take the `-ImageNetworkPath` and convert it to a local path, but then it will check to make sure the supplied `-ImageLocalPath` is equal to the converted network path. If this is the case, then what is the point of having a local path if network path is required and will convert down to the same local path?

Additionally, this is not how the examples in the script (granted these are probably outdated):

```
.EXAMPLE
        New-PSDCImage -SourceSqlInstance SQLDB1 -DestinationSqlInstance SQLDB2 -ImageLocalPath C:\Temp\images\ -Database DB1 -CreateFullBackup

        Create an image for databas DB1 from SQL Server SQLDB1. The temporary destination will be SQLDB2.
        The image will be saved in C:\Temp\images.
    .EXAMPLE
        New-PSDCImage -SourceSqlInstance SQLDB1 -DestinationSqlInstance SQLDB2 -ImageLocalPath C:\Temp\images\ -Database DB1 -UseLastFullBackup

        Create an image from the database DB1 on SQLDB1 using the last full backup and use SQLDB2 as the temporary database server.
        The image is written to c:\Temp\images
```

So I guess the question is what am I missing here about this parameter? From the examples and the naming of it, I assumed you could give either a network share to save the images, or a local path that the script is running on.

My understanding might also be complicated by the fact that I'm not using remote hosts in my evaluation and testing - all my commands are running on a single host with a single sql server instance and aren't communicating with others hosts, so maybe I'm missing a big piece of the puzzle 😋
