### ISSUE TITLE
Error when running Set-PSDCConfiguration without parameters

### ISSUE THREAD

**Issue by blitzmann** [sqlcollaborative/PSDatabaseClone#72]
**Before submitting the bug**
- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

**Describe the bug**
When running `Set-PSDCConfiguration`, the user is supposed to receive an interaction in which the scripts asks the user for various bit of information. This does not happen. Instead, the following error happens:

```
PS C:\Users\Administrator\Desktop\PSDatabaseClone> Set-PSDCConfiguration
Test-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
At line:218 char:35
+         if (-not (Test-Path -Path $Path)) {
+                                   ~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.TestPathCommand
 
WARNING: [21:48:40][Set-PSFConfig] Could not update configuration: PSDatabaseClone.informationstore.path | Failed validation: Is an empty string: 
```

**To Reproduce**
Run `Set-PSDCConfiguration` without parameters

**Expected behavior**
Interactive prompt should appear

**Comment by sanderstad** [comment]
Merged in development
